[#7] Add Footer UI
f-lab-edu/eqcm pull request #10
Opened 2024-09-15 17:34 UTC by rarlala

## 작업 내역
- 폰트 설정 오타로 적용되지 이슈 수정 a24f57d46ea0880c14130e50d89faa79a1f1b578
- Footer PC UI 작업 5fb5b54cf9767aa82e727954c400e7710a0cabb3
- Footer Mobile UI 작업 5d48ebeae03c9115497cf23375af09e6c0ee5e0d
- vh에서 header와 footer를 제외한 공간에 home 영역이 가득차도록 스타일 수정 0b4a5889ef4a1985e5f4dea7dbe6d788a1f52e08

2024-09-16 03:38 UTC, f-lab-jake requested changes

2024-09-16 03:38 UTC, f-lab-jake commented on src/constants/footer.tsx
> +export const FOOTER_SNS_LIST = [
복잡한 상수 데이터엔 타입 시그니쳐를 넣으세요. 사소한 오타가 피곤한 문제를 만들수 있습니다.

2024-09-16 03:38 UTC, f-lab-jake commented on src/components/footer/csButton.tsx
> +const CsButton = memo(function Button({ title }: { title: string }) {
props는 `type Props = `정도로 분리해주세요.
코드가 길어지더라도 적용가능한 일관된 스타일이 필요합니다.

2024-09-16 15:45 UTC, rarlala commented on src/constants/footer.tsx
> +export const FOOTER_SNS_LIST = [
넵~ [c3504f5](https://github.com/f-lab-edu/eqcm/pull/10/commits/c3504f5f13ccd9e4c01a1294fdbfc894c3ba2e0a)에 수정했습니다!

2024-09-16 15:52 UTC, rarlala commented on src/components/footer/csButton.tsx
> +const CsButton = memo(function Button({ title }: { title: string }) {
넵~ [96faae4](https://github.com/f-lab-edu/eqcm/pull/10/commits/96faae4f4cbcbe7af59a8e9a413df1dc41dda9cb) 헤더에도 prop를 사용하는 부분이 있어 함께 수정했습니다!

2024-09-18 06:17 UTC, f-lab-jake approved these changes

2024-09-19 18:02 UTC, merged