[#9] Add Join Page
f-lab-edu/eqcm pull request #14
Opened 2024-09-20 12:21 UTC by rarlala

## 작업 내역
회원가입 flow UI 및 react-hook-form + zod를 활용한 validation check 처리
- 1단계 : 약관동의 a6f95fb9c4225412c8e16f3f6e22013ecde96fc4
- 2단계 : 이에일 입력 709da028207e2e8413d4105302c070607c74be0b
- 3단계 : 비밀번호 입력 6c825bea09fa47981d3ed298bca3fb38a490144a
- 4단계 : 핸드폰 번호 입력 및 본인인증 17fed906f71835824ede52a4bd3b359f88553a08
- 5단계 : 이름, 생년월일 입력 및 가입 완료 620c9b6325c31658a0c39b9a918e3dd39057de68

## 작업 화면

### 약관 동의

https://github.com/user-attachments/assets/28410663-d934-42f0-be8b-ef5f1d0d8fa1

### 이메일 입력

https://github.com/user-attachments/assets/0ea5f882-6e44-4386-976d-954398bc8a49

### 비밀번호 입력

https://github.com/user-attachments/assets/89d940f8-20d9-49f4-a1f4-16303c4c2bf6

### 핸드폰 번호 입력 및 본인인증

https://github.com/user-attachments/assets/0cc8c572-6eb7-4ee8-8f81-33081ea519ef

### 이름, 생일 입력 및 가입완료

https://github.com/user-attachments/assets/fd0c8ae6-3fd1-4dd9-b622-f8596da685f3

2024-09-21 00:30 UTC, f-lab-jake requested changes

2024-09-21 00:30 UTC, f-lab-jake commented on src/app/join/page.tsx
> +  });
일찌감치 react-hook-form같은 라이브러리 쓰는게 속편합니다. 조금만 복잡해져도 필요해져요.

2024-09-25 05:41 UTC, rarlala commented on src/app/join/page.tsx
> +  });
위 부분 궁금한 점이 있습니다~!
현재 회원가입이 스텝으로 처리가 이루어지고 있습니다.
근데 스텝과 별도로 정보는 다 취합해서 보내야 하니 상위 컴포넌트에 정보를 하나로 취합하기 위한 상태구조인데요!
스텝별 내부 컴포넌트에서 react-hook-form을 쓰고 있는데 하나 더 감싸는 구조가 필요한 건지 모르겠어요...!

2024-09-28 05:30 UTC, f-lab-jake approved these changes

2024-09-28 05:30 UTC, f-lab-jake commented on src/components/join/passwordJoinForm.tsx
> +  onChangeData: (id: keyof UserDataType, value: boolean | string) => void;
잘 했습니다.

2024-09-28 09:19 UTC, merged