[#20] Add Home Page
f-lab-edu/eqcm pull request #21
Opened 2024-09-28 20:20 UTC by rarlala

## 작업 내역
- 메인 페이지 기본 html 및 css 설정 ac56342f9168e87e7aafe6cf8f0200870f585d59
- Banner 컴포넌트 구현 be17f79eb5fac945990e7144b9850f6aba526812
- BoxBanner 컴포넌트 구현 c5d99e5cab01ae7a975009c3d6e8c5274e0098f0
- BoxSlider 컴포넌트 구현([swiper](https://swiperjs.com/react) 라이브러리 사용) c9aaffec86fc752e61bb6cd036623f03707eff34
- 메인페이지 우측 영역 Masonry Layout 구현 및 메인 페이지 컴포넌트 분리 ([ma](https://github.com/cedricdelpoux/react-responsive-masonry#readme)를 사용) 69d8ab7c39a1290ad1c0632bf1f489f1708db6a0
  - 현재 29cm의 tablet 영역 UI가 UX 상으로 좋지 않다고 판단해 breakpoint를 똑같이 처리하지 않음

29cm UI | 개선한 UI (eqCM)
-- | --
 ![스크린샷 2024-09-28 오후 10 54 39](https://github.com/user-attachments/assets/76e14ddb-4331-4ed3-97fd-4823c9443e50)   |  ![스크린샷 2024-09-29 오전 12 55 38](https://github.com/user-attachments/assets/78545e0d-beb3-44b6-8a3e-f2343c465b1c)
- 모바일 메인 배너 슬라이드 컴포넌트 구현

## 작업 화면
PC
### Banner 컴포넌트

### BoxBanner 컴포넌트

### BoxSlider 컴포넌트

### 메인페이지

Mobile
### 모바일 메인 배너 슬라이드 컴포넌트

---
## 문의사항
1. swiper를 사용할 때 29cm와 동일한 높이값 설정의 어려움 이슈
2. pinterest와 같은 UI를 구성하기 위해 [ma](https://github.com/cedricdelpoux/react-responsive-masonry#readme) 라이브러리를 활용했는데, 이 외의 방법이 있었을지 궁금합니다.

2024-09-30 01:59 UTC, f-lab-jake requested changes

2024-09-30 01:59 UTC, f-lab-jake commented on src/components/main/boxSection.tsx
> +          })}
요거를 그냥 children으로 받는건 어떨까요?

2024-09-30 12:03 UTC, rarlala commented on src/components/main/boxSection.tsx
> +          })}
넵~ [9870934](https://github.com/f-lab-edu/eqcm/pull/21/commits/9870934df5a80346922e1031c27d65110217643c) 수정했습니다~!

2024-10-01 02:07 UTC, f-lab-jake requested changes

2024-10-01 02:07 UTC, f-lab-jake commented on src/app/page.tsx
> +  });
`useSuspenseQuery` 씁시다

2024-10-01 02:07 UTC, f-lab-jake commented on src/types/main.ts
> +  boxes: (BannerType | BoxBannerType | BoxSliderType)[] | undefined;
이제 이 타입을 이제안쓸수있지 않나요?

2024-10-07 14:16 UTC, rarlala commented on src/app/page.tsx
> +  });
수정했습니다! 해당 부분에서 궁금한게 생겼어요!
useSuspenseQuery를 사용하면 Query를 호출하는 부분 윗 단의 컴포넌트에 Suspense를 감싸 fallback으로 ui를 전달해야하는 구조인데요~! 지금 저는 BannerSectionSkeleton과 BoxSectionSkeleton의 ui를 각각 다르게 설정해 보여주고 있어서요!

이렇게 컴포넌트마다 skeleton ui를 다르게 구현하고 싶은 경우에는 이렇게 내부에
1. Suspense를 감싼 컴포넌트
2. Skeleton을 위한 Loading 컴포넌트
3. Content를 표시할 컴포넌트 (useSuspenseQuery 위치)
이런 구조가 일반적인지 궁금합니다!

lazy loading 구현 관련해서 next/dynamic을 사용해서 해당 부분에 loading 컴포넌트를 전달했던 방식은 컴포넌트마다 loading ui가 표시되는 시점이 달라서 페이지 전체를 로딩하는 방식으로 표현되지 않아서 아쉬웠는데,
현재 방식으로 변경하니 로딩되고 한번에 그려지는 제가 의도한 방향과도 맞는 것 같아요! 
덕분에 Suspense에 대해서도 추가 학습해 알게되었습니다!

2024-10-07 14:37 UTC, rarlala commented on src/types/main.ts
> +  boxes: (BannerType | BoxBannerType | BoxSliderType)[] | undefined;
해당 타입을 fetch하는 부분에 정의해 사용하고 있어요!
useSuspenseQuery에는 불필요해져서 지웠습니다! 26244699d694a6ca35ac3a903ca2766bec4569f2

2024-10-08 10:14 UTC, f-lab-jake commented on src/app/page.tsx
> +  });
suspense가 내부적으로 어떻게 구현되었는지도 파악해옵시다.

2024-10-11 15:41 UTC, rarlala commented on src/app/page.tsx
> +  });
https://sckimynwa.medium.com/suspense-deep-dive-code-implementation-e766582a7366
위 글을 읽어봤어요!

요약해보자면 component가 처리될 때,
그 컴포넌트가 suspense component면 updateSuspenseComponent 로직을 타게되고
showFallback 플래그에 따라서 true면 fallback ui를 보여주고 원래의 children은 mountSuspenseFallbackChildren로 hidden 처리, false면 원래의 children을 보여주는 mountSuspensePrimaryChildren를 실행해 보여지는 상태로 표시합니다.

데이터가 다 로딩되었는지 판단하기 위해서 비동기 완료 여부를 판단하기 위해 wrapPromise 형태를 반환하고 promise의 반환값에 따라 처리됩니다. 성공이면 원래의 컴포넌트 보여주고, 에러면 에러처리, pending이면 fallback 처리합니다.
이렇게까지 이해했습니다.

2024-10-12 07:03 UTC, f-lab-jake commented on src/components/main/boxSection.tsx
> +          })}
`data`대신에 children으로 받잔 얘기였습니다

2024-10-21 10:46 UTC, rarlala commented on src/components/main/boxSection.tsx
> +          })}
[80b182d](https://github.com/f-lab-edu/eqcm/pull/21/commits/80b182daff0a77ce03510a5cf600f2c54f54a857) children 형태로 받도록 수정했습니다

2024-10-22 05:36 UTC, f-lab-jake requested changes

2024-10-22 05:36 UTC, f-lab-jake commented on src/app/page.tsx
> +            return null;
이거 빼도 타입에러 안나지 않나요?

2024-10-22 05:36 UTC, f-lab-jake commented on src/components/main/boxSection.tsx
>  };
`PropsWithChildren`이라는 타입이 있습니다

2024-10-22 11:51 UTC, f-lab-jake requested changes

2024-10-22 11:51 UTC, f-lab-jake commented on src/components/product/optionStepper.tsx
> +            onChangeCount({ index, count: parseFloat(e.target.value) })
왜 `parseFloat`인가요?

2024-10-22 11:51 UTC, f-lab-jake commented on src/components/product/optionStepper.tsx
> +  index: number;
여기서 `index` props가 오로지 `onChangeCount`에서 다시 넘겨주기 위함인가요?

2024-10-22 11:51 UTC, f-lab-jake commented on src/components/product/productOptions.tsx
> +  const [state, dispatch] = useReducer(reducer, init(options));
https://dev.to/sathishskdev/using-usereducer-and-redux-toolkit-together-a-powerful-combination-for-state-management-3b2h
여기보니까 `creatSlice`같은 헬퍼를 `useReducer`랑 같이 쓸수도 있어보이네요. 가능하다면 적용해보면 좋겠어요.

2024-10-22 11:51 UTC, f-lab-jake commented on src/components/product/productOptions.tsx
> +  };
중복되는 패턴을 줄이는 헬퍼함수를 고안해보세요.

2024-10-22 12:29 UTC, rarlala commented on src/app/page.tsx
> +            return null;
[043d964](https://github.com/f-lab-edu/eqcm/pull/21/commits/043d964339b93fd8a65930d9d6087a3ccd4b4719)
넵! 마지막 부분을 return하도록 수정했습니다

2024-10-22 12:44 UTC, rarlala commented on src/components/product/optionStepper.tsx
> +            onChangeCount({ index, count: parseFloat(e.target.value) })
[9a19d69](https://github.com/f-lab-edu/eqcm/pull/21/commits/9a19d6962d01d25319de1aa7dd614e8f07b5f168) parseInt인데 parseFloat이 적용되어있었네요..! 수정했습니다

2024-10-22 12:55 UTC, rarlala commented on src/components/product/optionStepper.tsx
> +  index: number;
[3c0c17b](https://github.com/f-lab-edu/eqcm/pull/21/commits/3c0c17b34097c2a5fe6eb9b2a34056dd05ae981d) 아! 맞아요. 이해했습니다! index를 넘기기 전에 함수를 커링 형태로 변경해 index를 미리 받고 넘기도록 수정했습니다.

2024-10-22 13:10 UTC, rarlala commented on src/components/product/productOptions.tsx
> +  };
[9522030](https://github.com/f-lab-edu/eqcm/pull/21/commits/9522030e22356ef5b24d284e19ab458788fbaea7) 넵~! type과 payload를 넘기도록 수정했습니다.

2024-10-22 16:03 UTC, f-lab-jake commented on src/components/product/optionStepper.tsx
> +  index: number;
네 잘 고쳤습니다. 기존 구현에 어떤 문제가 있는지 설명해볼까요? 구체적으로 문제가 되는 시나리오를 들수있으면 좋습니다.

2024-10-22 16:04 UTC, f-lab-jake requested changes

2024-10-22 16:04 UTC, f-lab-jake commented on src/components/product/productOptions.tsx
> +    onChangeState(ProductActionType.CHANGE_COUNT, { index, count });
`onChangeCoung = onChangeState(ProductActionType.CHANGE_COUNT)` 와 같은 형태가 되도록 고쳐보세요.

2024-10-22 17:58 UTC, rarlala commented on src/components/product/productOptions.tsx
> +    onChangeState(ProductActionType.CHANGE_COUNT, { index, count });
[989bebb](https://github.com/f-lab-edu/eqcm/pull/21/commits/989bebb04cdc2731db26e763a2ad8354fb82a57e) 해당 함수도 커링 방식으로 수정했습니다!

2024-10-23 05:02 UTC, rarlala commented on src/app/page.tsx
> +  });
Suspense에서 내부적으로 데이터가 로딩되지 않았을 때 throw를 하는 이유는 동기적인 처리에서 데이터를 기다려줄 방법이 없기 때문에 자바스크립트의 예외 처리를 이용하기 위합니다.
throw Promise를 한 후, Suspense는 내부적으로 componentDidCatch를 사용해 throw 된 Promise를 잡아내고 fallback을 보여줍니다. Promise가 완료되면 다시 렌더링 처리를 하게 됩니다.

2024-10-28 06:48 UTC, f-lab-jake approved these changes

2024-10-30 11:18 UTC, merged

2024-10-31 06:59 UTC, rarlala commented on src/components/product/optionStepper.tsx
> +  index: number;
**[이전 코드의 문제점]**

- OptionStepper는 옵션의 개수를 조정하는 역할만 수행해야한다.
- OptionStepper를 사용하는 부분에서 index가 무조건적으로 필요해져 불필요한 제약이 추가되었고, 이는 컴포넌트의 재사용성을 떨어뜨린다.
    - index를 넘기는 이유는 ProductOptions Component의 onChange 내 dispatch로 action을 전달하는 값에 index가 필요했기 때문이다.
        
        → 즉, index는 OptionStepper Component를 사용하기 위한 필수 조건이 아니라 productOptions에서 필요했던 부분이었다.
        
- OptionStepper를 처음 보는 동료의 입장에서는 이 코드에 index가 왜 필요한지 이전 사용된 코드를 통해 분석해야한다. index가 ProductOptions Component에서만 필요한 값이라는 것을 인지하면 ProductOptions Component도 수정해야한다.

**[수정된 코드의 장점]**

- Option Stepper Component의 재사용성 및 유지보수성이 높아진다.
    - 표시할 숫자값과 그 숫자값을 변경하기 위한 onChange 함수만을 전달하면 된다.
- Option Stepper Component의 책임 분리, 목적이 분명해진다.
    
    ‘Options Stepper로 받는 onChangeCount는 Stepper를 클릭하면 number를 증감시킨다.’
    
    즉, 컴포넌트간의 결합도를 줄이고, 각 컴포넌트가 자신의 역할에만 집중하도록 개선되었다.