[#17] Connect join/email api
f-lab-edu/eqcm pull request #22
Opened 2024-10-01 13:35 UTC by rarlala

# 아직 작업중인 PR입니다!

## 작업 내역
- email로 회원가입 api 연동 39f7c03360430e6f61c046939f95c79c23061bb3
- 전달 데이터 형태 오류 수정 0d65f556d3c0bb90845f0ab1e4a30cee6967eb34

2024-10-13 07:23 UTC, f-lab-jake requested changes

2024-10-13 07:23 UTC, f-lab-jake commented on src/app/api/auth/[...nextauth]/route.ts
> +      },
일반적으론 그냥 error를 전파시키도록 하는게 낫습니다. 로그인에 왜 실패햇는지 알고싶을수 있어요.

2024-10-13 07:23 UTC, f-lab-jake commented on src/app/api/auth/[...nextauth]/route.ts
> +      },
아 `next-auth`에서 요구하는 설계인가요?

2024-10-13 07:23 UTC, f-lab-jake commented on src/app/join/page.tsx
> +      setStep(5);
요런코드를 피해보세요. `useReducer`를 쓰거나, 아니면 step에 이름을 주고 그걸 쓰세요.

2024-10-13 07:23 UTC, f-lab-jake commented on src/components/join/personalInfoForm.tsx
> +    requestJoin.mutate();
`requestJoin`을 인자로 받아서 `requestJoin.mutate`를 하는 이유가, `onChangeData`를 여러번 불러야하기 때문에 `onChangeData`가 `requestJoin`을 처리하도록 만들수 없어서인가요?

2024-10-13 07:23 UTC, f-lab-jake commented on src/fetch/auth.ts
> +    throw new Error('Failed to fetch agreement info');
요런 패턴도 에러 내용을 일부러 까먹는 패턴입니다.

2024-10-16 03:06 UTC, rarlala commented on src/app/api/auth/[...nextauth]/route.ts
> +      },
넵! next-auth에서 인증에 실패하면 null을 반환해야 사용자 인증이 되지 않았다고 간주해서, 로그인 페이지로 리다이렉트 처리되게끔 구현되어있더라고요! 그래서 throw new Error하는 것이 아니라 console.error()로 표시해두었습니다..!

2024-10-16 03:11 UTC, rarlala commented on src/components/join/personalInfoForm.tsx
> +    requestJoin.mutate();
아니요! onChangeData를 여러개 부르는 것과 상관없이 데이터를 모두 저장한 뒤, 
해당 시점에 api를 호출하는 것이 맞다고 판단해 인자로 받아 처리한 부분입니다!

2024-10-16 03:15 UTC, rarlala commented on src/fetch/auth.ts
> +    throw new Error('Failed to fetch agreement info');
'일부러 까먹는 패턴' 의 의미를 잘 모르겠습니다!

2024-10-16 03:36 UTC, rarlala commented on src/app/join/page.tsx
> +      setStep(5);
넵! [00f16de](https://github.com/f-lab-edu/eqcm/pull/22/commits/00f16dec2681f6c5e95a4bd9a17ba88127accbd5) 이름을 주는 방식으로 수정했습니다!

2024-11-05 01:08 UTC, f-lab-jake approved these changes

2024-11-10 08:26 UTC, merged