[#20] refactor: useReducer + RTK combination
f-lab-edu/eqcm pull request #27
Opened 2024-10-31 17:45 UTC by rarlala

## 작업 내역
- 상품 옵션 상태 관리를 위해 `useReducer`를 사용한 코드를 `useReducer + RTK` 조합으로 리팩토링
  - RTK의 도입으로 내장된 `immer`를 활용하여 불변성 관리가 용이해졌고, 액션 타입 정의 등 불필요한 보일러플레이트 코드가 감소함
  - 파일을 hook으로 분리하여 컴포넌트의 코드 복잡성을 줄이고, 가독성을 향상시켰습니다. 이로 인해 유지보수가 용이해짐
  
## 참고 자료
- [Using useReducer and Redux Toolkit Together](https://dev.to/sathishskdev/using-usereducer-and-redux-toolkit-together-a-powerful-combination-for-state-management-3b2h)

2024-11-01 06:03 UTC, f-lab-jake requested changes

2024-11-01 06:03 UTC, f-lab-jake commented on src/components/product/productOptions.tsx
> +  optionType?: string;
이건 원래가 더 낫지않나요? 왜 더 느슨한 타입으로 바꿨나요?

2024-11-01 06:03 UTC, f-lab-jake commented on src/components/product/productOptions.tsx
>      };
이런 함수는 캡쳐한 변수가 없으니까 밖으로 꺼내도 되겠죠.

2024-11-01 06:03 UTC, f-lab-jake commented on src/components/product/productOptions.tsx
> +  const [state, dispatch] = useReducer(reducer, getInitialState());
`getInitialState()` => `getInitialState` 뭐가다를까요?

2024-11-01 06:03 UTC, f-lab-jake commented on src/components/product/productOptions.tsx
> +
두 `useEffect` 다 사용을 피할수 있어보입니다.

2024-11-01 06:03 UTC, f-lab-jake commented on src/components/product/productOptions.tsx
> +              {formatWithCommas(totalPrice)}
`numeral`같은거 쓰시는건 어떨까요?

2024-11-01 06:03 UTC, f-lab-jake commented on src/store/useProductOptionsReducer.ts
> +    },
immer를 적용했다고 쓰셨는데 이런데 쓰면 딱 좋지 않낭요?

2024-11-02 17:21 UTC, rarlala commented on src/components/product/productOptions.tsx
> +  optionType?: string;
이 부분은 제가 타입을 잘못 지정했습니다. option으로 들어갈 값은 size, color 같은 값이 들어가야하는데 값에 해당하는 타입으로 적용되어 string으로 수정했었습니다. 현재는 Option을 정의해 놓은 부분이 있어서 그 타입을 사용하도록 수정했습니다.

2024-11-02 17:33 UTC, rarlala commented on src/components/product/productOptions.tsx
> +
넵! 위 useEffect는 useReducer initializer에서 적용되도록 했고, initialState에 defaultOption이 불필요해져 삭제했습니다.
아래 useEffect는 useMemo를 활용해 값을 메모해 최적화하도록 변경했습니다.

useMemo와 useCallback의 차이는
useMemo는 **값**을 메모이제이션해서, dependency가 변경되지 않으면 동일한 값을 리턴해 계산이 다시 수행되지 않기 때문에 연산을 다시할 필요가 없어 복잡한 로직을 수행할 때 성능상 이점을 줍니다.

useCallback은 **함수**를 메모이제이션해서, dependecy가 변경되지 않으면 동일한 함수를 반환합니다. 이는 memo를 사용하는 하위 컴포넌트에 해당 함수를 전달한 경우 렌더링마다 함수 참조가 변경되는 것을 막아 매번 하위 컴포넌트가 리렌더링되는 것을 방지해주는 이점이 있습니다.

현재 totalPrice는 하위 컴포넌트에 전달하는 것이 아닌 옵션이 변경되지 않은 경우 동일한 값을 사용하도록 해 성능상 이점을 얻을 수 있는 구조로 useMemo를 사용하는 것이 맞다는 점을 이해했습니다!

2024-11-02 17:56 UTC, rarlala commented on src/components/product/productOptions.tsx
> +  const [state, dispatch] = useReducer(reducer, getInitialState());
getInitialState()는 useReducer가 호출될때마다 매번 getInitialState이 호출되어 다시 계산하고. getInitialState는 함수의 참조를 넘겨 처음 렌더링할때만 호출됩니다.
const [state, dispatch] = useReducer(reducer, null, getInitialState); 이렇게 정의했어야 한번만 연산을 수행할 수 있는 형태였네요!

2024-11-02 18:03 UTC, rarlala commented on src/components/product/productOptions.tsx
>      };
넵! 중복 제거의 목적으로 필요할까 싶어 작성했는데, 수정했습니다!

2024-11-02 18:12 UTC, rarlala commented on src/store/useProductOptionsReducer.ts
> +    },
아! 그렇네요...! 수정했습니다!

2024-11-02 18:23 UTC, rarlala commented on src/components/product/productOptions.tsx
> +              {formatWithCommas(totalPrice)}
넵! 사용하는 곳이 많아서 formatWithCommas는 유지하고 내부적으로 numeral을 사용하도록 했습니다!

2024-11-03 07:44 UTC, f-lab-jake approved these changes

2024-11-03 17:39 UTC, merged